### PR TITLE
Fix a number of issues

### PR DESCRIPTION
**Pull request by snoyberg**
These were uncovered when researching commercialhaskell/stack#105. What
I discovered:

* There was an extra layer of `.git` directories in computed paths
* The HEAD file should be added dependently regardless of whether it's a
  detached head
* Add a missing check in relRef for newline
* Switch newline handling to check both CR and LR for Windows support

### CODE REVIEW

**Comment by snoyberg** [comment]
Bumping

**Comment by bitemyapp** [comment]
Bump

**Comment by ulidtko** [comment]
FWIW, tested the patch — it does fix `gitrev` failing to invalidate the TH splice on git changes.

Absolutely must-merge.

**Comment by yitz-zoomin** [comment]
Ping @acfoltzer pls pls merge this PR. Thanks.

**Comment by acfoltzer** [comment]
I'm fine with merging this but I do not develop Haskell any longer, so have no means of testing it myself. Please feel free to make a fork if you'd like to continue further development of this project.

**Pull request merged**
